export interface AuditEventRecord {
  id: string;
  action: string;
  actor: { email: string; displayName: string };
  timestamp: { seconds: number } | null;
  metadata: Record<string, unknown>;
}

export interface SubmissionSummary {
  id: string;
  file_name: string;
  airlineName: string;
  status: string;
  extractedData?: { tailNumber?: string };
}

function formatMetadata(action: string, metadata: Record<string, unknown>): string {
  switch (action) {
    case "submission.status_changed":
      return `${metadata.from} → ${metadata.to}`;
    case "submission.comment_added":
      return `"${metadata.commentPreview}"`;
    case "ocr.completed":
      return `Tail: ${metadata.tailNumber} · Confidence: ${metadata.confidenceScore}% · ${metadata.complianceStatus}`;
    case "ocr.failed":
      return `Error: ${metadata.errorMessage}`;
    case "submission.created":
      return `${metadata.fileName} (${metadata.fileType})`;
    default:
      return JSON.stringify(metadata);
  }
}

function formatTimestamp(ts: { seconds: number } | null): string {
  if (!ts) return "—";
  return new Date(ts.seconds * 1000).toISOString().replace("T", " ").slice(0, 19) + " UTC";
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function filenameDate(): string {
  return new Date().toISOString().slice(0, 10);
}

export function exportAuditCSV(
  submission: SubmissionSummary,
  events: AuditEventRecord[]
): void {
  const tailNumber = submission.extractedData?.tailNumber || submission.id;
  const header = ["Timestamp", "Action", "Actor", "Details"];
  const rows = events.map((e) => [
    formatTimestamp(e.timestamp),
    e.action,
    e.actor.email,
    formatMetadata(e.action, e.metadata).replace(/"/g, '""'),
  ]);

  // UTF-8 BOM ensures Excel opens the file with correct encoding for CJK characters
  const bom = "﻿";
  const csv = bom + [header, ...rows]
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  triggerDownload(
    new Blob([csv], { type: "text/csv;charset=utf-8;" }),
    `audit-${tailNumber}-${filenameDate()}.csv`
  );
}

// Uses browser print-to-PDF so system fonts (PingFang TC, Microsoft JhengHei, etc.)
// render Traditional Chinese correctly — jsPDF's built-in fonts don't include CJK glyphs.
export function exportAuditPDF(
  submission: SubmissionSummary,
  events: AuditEventRecord[]
): void {
  const tailNumber = submission.extractedData?.tailNumber || submission.id;

  const rows = events
    .map(
      (e, i) => `
      <tr style="background:${i % 2 === 0 ? "#f8fafc" : "#fff"}">
        <td>${formatTimestamp(e.timestamp)}</td>
        <td>${e.action}</td>
        <td>${e.actor.email}</td>
        <td>${formatMetadata(e.action, e.metadata)}</td>
      </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Audit Report — ${tailNumber}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: "PingFang TC", "Microsoft JhengHei", "Noto Sans TC",
                 "Apple SD Gothic Neo", "Hiragino Sans", Arial, sans-serif;
    font-size: 11px;
    color: #0f172a;
    padding: 32px;
  }
  h1 { font-size: 18px; font-weight: 700; margin-bottom: 12px; }
  .meta { color: #64748b; font-size: 10px; line-height: 1.8; margin-bottom: 16px; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; font-size: 10px; }
  thead tr { background: #f1f5f9; }
  th {
    text-align: left; padding: 6px 8px;
    font-size: 9px; font-weight: 700;
    color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em;
  }
  td { padding: 6px 8px; color: #334155; vertical-align: top; word-break: break-word; }
  td:nth-child(1) { white-space: nowrap; width: 130px; }
  td:nth-child(2) { width: 120px; }
  td:nth-child(3) { width: 130px; }
  td:nth-child(4) { }
  .footer { margin-top: 24px; font-size: 9px; color: #94a3b8; }
  @media print {
    body { padding: 16px; }
    @page { size: A4; margin: 16mm; }
  }
</style>
</head>
<body>
  <h1>Compliance Audit Report</h1>
  <div class="meta">
    <div>Submission ID: ${submission.id}</div>
    <div>Tail #: ${tailNumber}</div>
    <div>Airline: ${submission.airlineName}</div>
    <div>File: ${submission.file_name}</div>
    <div>Status: ${submission.status}</div>
    <div>Exported: ${new Date().toUTCString()}</div>
  </div>
  <hr>
  <table>
    <thead>
      <tr>
        <th>Timestamp</th>
        <th>Action</th>
        <th>Actor</th>
        <th>Details</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">Generated by SkyGate Portal — ${new Date().toUTCString()}</div>
  <script>window.onload = () => { window.print(); }<\/script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
